### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by imperugo** [sandrinodimattia/WindowsAzure-IPAddressRestriction#2]
Hi I'm trying the package (downloaded from nuget) but there is no way to deploy the cloud server (web role).

Everytime I use your exaple and try to deploy I got this message:

Your role instances have recycled a number of times during an update or upgrade operation. This indicates that the new version of your service or the configuration settings you provided when configuring the service prevent the role instances from running. Verify your code does not throw unhandled exceptions and that your configuration settings are correct and then start another update or upgrade operation.

**Comment by dinesh29245** [comment]
Hi
I am also facing the same issue. This package is working fine only with azure sdk1.8. 
It is not working with 2.1 & 2.2 . Only difference I found is, .Net trust level option is missing in these sdk which may be root cause.

**Comment by sandrinodm** [comment]
This package is no longer supported, switch to ACL instead: http://blogs.msdn.com/b/walterm/archive/2014/04/22/windows-azure-paas-acls-are-here.aspx

**Comment by HemanthGali** [comment]
I'm facing same issue if I use Xero.NetStandard.OAuth2 (latest version) and Xero.NetStandard.OAuth2Client (latest version) packages in my solution. Please let me know if any fix for this.
